FROM python:3.12.10-slim

WORKDIR /app

# Устанавливаем зависимости
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Копируем остальные файлы
COPY .env .
COPY common/ ./common/
COPY bot/ ./bot/

# Запуск (используем -m для модулей)
CMD ["python", "-m", "bot"]