FROM python:3.12.10-slim

# Устанавливаем рабочую директорию
WORKDIR /app

# Копируем requirements.txt
COPY requirements.txt .

# Устанавливаем зависимости
RUN pip install --no-cache-dir -r requirements.txt

# Копируем остальные файлы
COPY .env .
COPY common/ ./common/
COPY bot/ ./bot/

# Запуск (используем -m для модулей)
CMD ["python", "-m", "bot"]